# Docker image for CI testing of the DEEPaaS API
# Note there is probably no gpu in the CI server
#ARG tag=1.13.1-cuda11.6-cudnn8-runtime
ARG tag=2.3.1-cuda11.8-cudnn8-runtime
FROM pytorch/pytorch:${tag}
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    git \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel
RUN pip3 install --no-cache-dir 'tox<4.0.0'
CMD ["sleep", "infinity"]
